In [1]:
# 1 
# Вкладник поклав 50000 умовних одиниць на три різні рахунки в три різні банки. 
# За першим рахунком виплати становитимуть 5% річних, по другому – 7% річних та по третьому 6% річних. 
# Відомо, що через рік вкладник отримав за відсотками суму в 2250 у.о. з першого та другого банку та суму в 1400 у.о. 
# з першого та третього банку. Скільки умовних одиниць він поклав на кожен рахунок спочатку?

import numpy as np
a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
b = np.matrix("50000;2255;1400")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

# a = np.array([[1,1,1], [0.05,0.07,0], [0.05,0, 0.06]])
# b = np.array([50000,2255,1450])
# x = np.linalg.solve(a,b)
# print(x)

[[10130.43478261]
 [24978.26086957]
 [14891.30434783]]


In [6]:
# 2
# На складі зберігаються мобільні телефони iPhone 6, iPhone 11, iPhone 12 моделей. 
# Всього 1328 екземплярів. Моделей iPhone 6 на 120 менше, ніж моделей iPhone 11, та на 100 більше, 
# ніж моделей iPhone 12. Скільки моделей кожного виду на складі?

a = np.matrix("1,1,1;1,-1,0;1,0,-1")
b = np.matrix("1328;-120;100")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[436.]
 [556.]
 [336.]]


In [13]:
# 3
# Складіть канонічне рівняння еліпсоїда, що проходить через три точки А B C

# система  рівнянь
# 3/a^2 + 3/c^2 = 1
# 6/a^2 + 1/4b^2 = 1
# 1/a^2 + 1/3b^2 + 1c^2

# приведення лінійних рівнянь лінійної форми
# u = 1/a^2 
# v = 1/b^2
# w = 1/c^2

# система лінійних рівнянь для матриці для рішення в матричній формі
# 3u + 0v   + 3w = 1
# 6u +  v/4 + 0w = 1
#  u +  v/3 +  w = 1

# формула результату
# a^2 = u
# b^2 = v
# c^2 = w

import numpy as np
a = np.matrix("3,0,3;6,0.25,0;1,0.33,1")
b = np.matrix("1;1;1")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[0.08249158]
 [2.02020202]
 [0.25084175]]


In [13]:
# 4
# Складіть рівняння параболи що проходить через задані три точки (1,12), (3,54), (-1,2)
# система лінійних рівнянь
# a*1^2 + b*1 + c = 12
# a*3^2 + b*3 + c = 54
# a*(-1)^2 + b*(-1) + c = 2 

import numpy as np
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)


[[4.]
 [5.]
 [3.]]


In [15]:
# 5
# Складіть функцію get_polynom, яка за набором точок виду

import numpy as np

def get_polynom(coords):
    a = []
    b = []
    for x, y in coords:
        b.append(y)
        c = []
        for i in range(len(coords)):
            c.append(x ** i)
        a.append(c)
    return np.linalg.solve(a, b)

get_polynom([(1,12), (3,54), (-1,2)])

array([3., 5., 4.])